# Generated by Django 5.1 on 2024-08-15 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('skills_required', models.CharField(blank=True, max_length=255, null=True)),
                ('max_participants', models.IntegerField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('participants', models.ManyToManyField(blank=True, related_name='registered_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
