
version: 0.0
os: linux


hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 90
      runas: root

  AfterInstall:
    - location: scripts/pull_docker_image.sh
      timeout: 90
      runas: root

  ApplicationStart:
    - location: scripts/start_docker_container.sh
      timeout: 90
      runas: root

  ApplicationStop:
    - location: scripts/stop_docker_container.sh
      timeout: 90
      runas: root
